#!/usr/bin/env node
// Build 51 DUI/DWI Cost Calculator pages (all 50 states + index)
// Target CPC: $50-150/click — ultra-high legal niche

const fs = require('fs');
const path = require('path');

const states = {
  AL: { name: 'Alabama', abbr: 'AL', minFine: 600, maxFine: 5100, jailFirst: '0-365 days', jailSecond: '5 days-1 year', licenseSusp: '90 days', srFee: 100, igLock: 'Required (2nd+)', bac: 0.08, lookback: 5, dwiTerm: 'DUI', avgInsIncrease: 145, minAge: 21, impliedConsent: true, felonyAt: '4th offense', mandatoryMin: false, diversion: true },
  AK: { name: 'Alaska', abbr: 'AK', minFine: 1500, maxFine: 10000, jailFirst: '72 hours min', jailSecond: '20 days min', licenseSusp: '90 days', srFee: 200, igLock: 'Required (all)', bac: 0.08, lookback: 15, dwiTerm: 'DUI', avgInsIncrease: 160, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: true, diversion: false },
  AZ: { name: 'Arizona', abbr: 'AZ', minFine: 1250, maxFine: 150000, jailFirst: '10 days (1 suspended)', jailSecond: '90 days', licenseSusp: '90 days', srFee: 1500, igLock: 'Required (all)', bac: 0.08, lookback: 7, dwiTerm: 'DUI', avgInsIncrease: 175, minAge: 21, impliedConsent: true, felonyAt: '3rd in 7 years', mandatoryMin: true, diversion: false },
  AR: { name: 'Arkansas', abbr: 'AR', minFine: 150, maxFine: 5000, jailFirst: '1 day-1 year', jailSecond: '7 days-1 year', licenseSusp: '6 months', srFee: 150, igLock: 'Required (2nd+)', bac: 0.08, lookback: 5, dwiTerm: 'DWI', avgInsIncrease: 130, minAge: 21, impliedConsent: true, felonyAt: '4th offense', mandatoryMin: true, diversion: true },
  CA: { name: 'California', abbr: 'CA', minFine: 390, maxFine: 5000, jailFirst: '48 hours-6 months', jailSecond: '96 hours-1 year', licenseSusp: '6 months', srFee: 250, igLock: 'Required (all)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 195, minAge: 21, impliedConsent: true, felonyAt: '4th in 10 years', mandatoryMin: true, diversion: true },
  CO: { name: 'Colorado', abbr: 'CO', minFine: 600, maxFine: 5000, jailFirst: '5 days-1 year', jailSecond: '10 days-1 year', licenseSusp: '9 months', srFee: 200, igLock: 'Required (all)', bac: 0.08, lookback: 0, dwiTerm: 'DUI/DWAI', avgInsIncrease: 155, minAge: 21, impliedConsent: true, felonyAt: '4th offense (lifetime)', mandatoryMin: true, diversion: true },
  CT: { name: 'Connecticut', abbr: 'CT', minFine: 500, maxFine: 8000, jailFirst: '48 hours-6 months', jailSecond: '120 days-2 years', licenseSusp: '45 days', srFee: 175, igLock: 'Required (all)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 165, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: true, diversion: true },
  DE: { name: 'Delaware', abbr: 'DE', minFine: 500, maxFine: 7000, jailFirst: '0-6 months', jailSecond: '60 days-18 months', licenseSusp: '12 months', srFee: 143, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 150, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: true, diversion: true },
  FL: { name: 'Florida', abbr: 'FL', minFine: 500, maxFine: 5000, jailFirst: '0-6 months', jailSecond: '10 days-9 months', licenseSusp: '180 days-1 year', srFee: 150, igLock: 'Required (2nd+)', bac: 0.08, lookback: 0, dwiTerm: 'DUI', avgInsIncrease: 185, minAge: 21, impliedConsent: true, felonyAt: '3rd in 10 years or 4th', mandatoryMin: true, diversion: true },
  GA: { name: 'Georgia', abbr: 'GA', minFine: 300, maxFine: 5000, jailFirst: '10 days-12 months', jailSecond: '48 hours-12 months', licenseSusp: '1 year', srFee: 210, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 170, minAge: 21, impliedConsent: true, felonyAt: '4th in 10 years', mandatoryMin: true, diversion: false },
  HI: { name: 'Hawaii', abbr: 'HI', minFine: 250, maxFine: 5000, jailFirst: '48 hours-5 days', jailSecond: '5-30 days', licenseSusp: '1 year', srFee: 50, igLock: 'Required (all)', bac: 0.08, lookback: 10, dwiTerm: 'DUI/OUI', avgInsIncrease: 140, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: true, diversion: true },
  ID: { name: 'Idaho', abbr: 'ID', minFine: 500, maxFine: 5000, jailFirst: '0-6 months', jailSecond: '10 days-1 year', licenseSusp: '90-180 days', srFee: 175, igLock: 'Required (all)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 135, minAge: 21, impliedConsent: true, felonyAt: '3rd in 10 years', mandatoryMin: true, diversion: true },
  IL: { name: 'Illinois', abbr: 'IL', minFine: 500, maxFine: 25000, jailFirst: '0-1 year', jailSecond: '0-1 year', licenseSusp: '1 year', srFee: 500, igLock: 'Required (all)', bac: 0.08, lookback: 0, dwiTerm: 'DUI', avgInsIncrease: 180, minAge: 21, impliedConsent: true, felonyAt: '3rd offense (lifetime)', mandatoryMin: false, diversion: true },
  IN: { name: 'Indiana', abbr: 'IN', minFine: 500, maxFine: 10000, jailFirst: '0-60 days', jailSecond: '5 days-3 years', licenseSusp: '90 days-2 years', srFee: 250, igLock: 'Required (2nd+)', bac: 0.08, lookback: 7, dwiTerm: 'OWI', avgInsIncrease: 145, minAge: 21, impliedConsent: true, felonyAt: '2nd+ with prior felony', mandatoryMin: true, diversion: true },
  IA: { name: 'Iowa', abbr: 'IA', minFine: 625, maxFine: 6250, jailFirst: '48 hours-1 year', jailSecond: '7 days-2 years', licenseSusp: '180 days', srFee: 200, igLock: 'Required (2nd+)', bac: 0.08, lookback: 12, dwiTerm: 'OWI', avgInsIncrease: 140, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: true, diversion: true },
  KS: { name: 'Kansas', abbr: 'KS', minFine: 750, maxFine: 2500, jailFirst: '48 hours-6 months', jailSecond: '90 days-1 year', licenseSusp: '30 days', srFee: 250, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 150, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: true, diversion: true },
  KY: { name: 'Kentucky', abbr: 'KY', minFine: 200, maxFine: 5000, jailFirst: '2-30 days', jailSecond: '7 days-6 months', licenseSusp: '30-120 days', srFee: 150, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 135, minAge: 21, impliedConsent: true, felonyAt: '4th in 10 years', mandatoryMin: true, diversion: true },
  LA: { name: 'Louisiana', abbr: 'LA', minFine: 300, maxFine: 5000, jailFirst: '10 days-6 months', jailSecond: '30 days-6 months', licenseSusp: '90 days', srFee: 100, igLock: 'Required (all)', bac: 0.08, lookback: 10, dwiTerm: 'DWI', avgInsIncrease: 175, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: true, diversion: true },
  ME: { name: 'Maine', abbr: 'ME', minFine: 500, maxFine: 5000, jailFirst: '48 hours-364 days', jailSecond: '7 days-364 days', licenseSusp: '150 days', srFee: 50, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'OUI', avgInsIncrease: 130, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: true, diversion: false },
  MD: { name: 'Maryland', abbr: 'MD', minFine: 500, maxFine: 5000, jailFirst: '0-1 year', jailSecond: '0-2 years', licenseSusp: '6 months', srFee: 150, igLock: 'Required (all)', bac: 0.08, lookback: 5, dwiTerm: 'DUI/DWI', avgInsIncrease: 165, minAge: 21, impliedConsent: true, felonyAt: 'None (all misdemeanor)', mandatoryMin: false, diversion: true },
  MA: { name: 'Massachusetts', abbr: 'MA', minFine: 500, maxFine: 5000, jailFirst: '0-30 months', jailSecond: '60 days-30 months', licenseSusp: '1 year', srFee: 250, igLock: 'Required (2nd+)', bac: 0.08, lookback: 0, dwiTerm: 'OUI', avgInsIncrease: 175, minAge: 21, impliedConsent: true, felonyAt: '3rd offense (lifetime)', mandatoryMin: true, diversion: true },
  MI: { name: 'Michigan', abbr: 'MI', minFine: 100, maxFine: 5000, jailFirst: '0-93 days', jailSecond: '5 days-1 year', licenseSusp: '30 days + 150 restricted', srFee: 250, igLock: 'Required (2nd+)', bac: 0.08, lookback: 7, dwiTerm: 'OWI', avgInsIncrease: 160, minAge: 21, impliedConsent: true, felonyAt: '3rd offense (lifetime)', mandatoryMin: true, diversion: true },
  MN: { name: 'Minnesota', abbr: 'MN', minFine: 300, maxFine: 14000, jailFirst: '0-90 days', jailSecond: '30 days-1 year', licenseSusp: '90 days', srFee: 680, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'DWI', avgInsIncrease: 155, minAge: 21, impliedConsent: true, felonyAt: '4th in 10 years', mandatoryMin: true, diversion: false },
  MS: { name: 'Mississippi', abbr: 'MS', minFine: 250, maxFine: 5000, jailFirst: '0-48 hours', jailSecond: '5 days-1 year', licenseSusp: '90 days', srFee: 100, igLock: 'Required (2nd+)', bac: 0.08, lookback: 5, dwiTerm: 'DUI', avgInsIncrease: 140, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: false, diversion: true },
  MO: { name: 'Missouri', abbr: 'MO', minFine: 0, maxFine: 5000, jailFirst: '0-6 months', jailSecond: '0-1 year', licenseSusp: '30-90 days', srFee: 45, igLock: 'Required (2nd+)', bac: 0.08, lookback: 5, dwiTerm: 'DWI', avgInsIncrease: 150, minAge: 21, impliedConsent: true, felonyAt: '3rd offense (lifetime)', mandatoryMin: false, diversion: true },
  MT: { name: 'Montana', abbr: 'MT', minFine: 600, maxFine: 10000, jailFirst: '24 hours-6 months', jailSecond: '7 days-6 months', licenseSusp: '6 months', srFee: 200, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 155, minAge: 21, impliedConsent: true, felonyAt: '4th offense (lifetime)', mandatoryMin: true, diversion: true },
  NE: { name: 'Nebraska', abbr: 'NE', minFine: 500, maxFine: 10000, jailFirst: '7-60 days', jailSecond: '30-90 days', licenseSusp: '6 months', srFee: 130, igLock: 'Required (all)', bac: 0.08, lookback: 15, dwiTerm: 'DUI', avgInsIncrease: 140, minAge: 21, impliedConsent: true, felonyAt: '3rd offense', mandatoryMin: true, diversion: false },
  NV: { name: 'Nevada', abbr: 'NV', minFine: 400, maxFine: 5000, jailFirst: '2 days-6 months', jailSecond: '10 days-6 months', licenseSusp: '185 days', srFee: 100, igLock: 'Required (all)', bac: 0.08, lookback: 7, dwiTerm: 'DUI', avgInsIncrease: 165, minAge: 21, impliedConsent: true, felonyAt: '3rd in 7 years', mandatoryMin: true, diversion: true },
  NH: { name: 'New Hampshire', abbr: 'NH', minFine: 500, maxFine: 4000, jailFirst: '0-12 months', jailSecond: '17 days-12 months', licenseSusp: '9 months-2 years', srFee: 100, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'DWI', avgInsIncrease: 145, minAge: 21, impliedConsent: true, felonyAt: 'Aggravated DWI', mandatoryMin: true, diversion: false },
  NJ: { name: 'New Jersey', abbr: 'NJ', minFine: 250, maxFine: 1000, jailFirst: '0-30 days', jailSecond: '48 hours-90 days', licenseSusp: '3-12 months', srFee: 1000, igLock: 'Required (all)', bac: 0.08, lookback: 10, dwiTerm: 'DWI', avgInsIncrease: 190, minAge: 21, impliedConsent: true, felonyAt: 'None (all traffic offense)', mandatoryMin: true, diversion: false },
  NM: { name: 'New Mexico', abbr: 'NM', minFine: 300, maxFine: 5000, jailFirst: '0-90 days', jailSecond: '96 hours-364 days', licenseSusp: '1 year', srFee: 100, igLock: 'Required (all)', bac: 0.08, lookback: 0, dwiTerm: 'DWI', avgInsIncrease: 160, minAge: 21, impliedConsent: true, felonyAt: '4th offense (lifetime)', mandatoryMin: true, diversion: false },
  NY: { name: 'New York', abbr: 'NY', minFine: 500, maxFine: 10000, jailFirst: '0-1 year', jailSecond: '0-4 years', licenseSusp: '6 months', srFee: 750, igLock: 'Required (all)', bac: 0.08, lookback: 10, dwiTerm: 'DWI/DWAI', avgInsIncrease: 195, minAge: 21, impliedConsent: true, felonyAt: '2nd in 10 years', mandatoryMin: false, diversion: true },
  NC: { name: 'North Carolina', abbr: 'NC', minFine: 200, maxFine: 4000, jailFirst: '24 hours-24 months', jailSecond: '7 days-24 months', licenseSusp: '1 year', srFee: 100, igLock: 'Required (2nd+)', bac: 0.08, lookback: 7, dwiTerm: 'DWI', avgInsIncrease: 170, minAge: 21, impliedConsent: true, felonyAt: 'Habitual offender', mandatoryMin: true, diversion: false },
  ND: { name: 'North Dakota', abbr: 'ND', minFine: 500, maxFine: 3000, jailFirst: '2-30 days', jailSecond: '10 days-1 year', licenseSusp: '91 days', srFee: 50, igLock: 'Required (2nd+)', bac: 0.08, lookback: 7, dwiTerm: 'DUI', avgInsIncrease: 130, minAge: 21, impliedConsent: true, felonyAt: '3rd in 7 years', mandatoryMin: true, diversion: false },
  OH: { name: 'Ohio', abbr: 'OH', minFine: 375, maxFine: 10500, jailFirst: '3-180 days', jailSecond: '10-180 days', licenseSusp: '1-3 years', srFee: 475, igLock: 'Required (all)', bac: 0.08, lookback: 10, dwiTerm: 'OVI', avgInsIncrease: 155, minAge: 21, impliedConsent: true, felonyAt: '4th in 10 years', mandatoryMin: true, diversion: true },
  OK: { name: 'Oklahoma', abbr: 'OK', minFine: 0, maxFine: 5000, jailFirst: '10 days-1 year', jailSecond: '1-5 years', licenseSusp: '180 days', srFee: 200, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 145, minAge: 21, impliedConsent: true, felonyAt: '2nd offense (felony)', mandatoryMin: true, diversion: true },
  OR: { name: 'Oregon', abbr: 'OR', minFine: 1000, maxFine: 10000, jailFirst: '48 hours-1 year', jailSecond: '48 hours-1 year', licenseSusp: '1 year', srFee: 265, igLock: 'Required (all)', bac: 0.08, lookback: 0, dwiTerm: 'DUII', avgInsIncrease: 160, minAge: 21, impliedConsent: true, felonyAt: '3rd in 10 years', mandatoryMin: true, diversion: true },
  PA: { name: 'Pennsylvania', abbr: 'PA', minFine: 300, maxFine: 10000, jailFirst: '0-6 months', jailSecond: '5 days-6 months', licenseSusp: '12 months', srFee: 500, igLock: 'Required (2nd+)', bac: 0.08, lookback: 10, dwiTerm: 'DUI', avgInsIncrease: 170, minAge: 21, impliedConsent: true, felonyAt: '3rd+ high BAC', mandatoryMin: true, diversion: true },
  RI: { name: 'Rhode Island', abbr:>